/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Contact.java
 *
 * Created on Jul 24, 2017, 9:56:39 PM
 */

/**
 *
 * @author Ayush
 */
public class Contact extends javax.swing.JFrame {

    /** Creates new form Contact */
    public Contact() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel12.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel12.setText("Facsimile: +91-11-2389 9090");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(620, 530, 230, 14);

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel5.setText("Telephone: +91-11-2389 0909");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(620, 490, 230, 14);

        jLabel13.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel13.setText("Email: icld@ivorygroups.com");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(620, 450, 210, 20);

        jLabel15.setFont(new java.awt.Font("Baskerville Old Face", 1, 20));
        jLabel15.setText("Ivory Centre for Learning & Development");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(600, 400, 370, 30);

        jLabel33.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel33.setText("Facsimile: +91-11-2389 6008");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(620, 320, 230, 14);

        jLabel28.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel28.setText("Telephone: +91-11-2389 0808");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(620, 290, 250, 14);

        jLabel23.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel23.setText("Email: careers@ivorygroups.com");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(620, 260, 280, 14);

        jLabel10.setFont(new java.awt.Font("Baskerville Old Face", 1, 20));
        jLabel10.setText("Coorporate Human Resources");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(620, 220, 270, 20);

        jLabel31.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel31.setText("Facsimile: +91-11-2389 5005");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(630, 170, 260, 14);

        jLabel26.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel26.setText("Telephone: +91-11-2389 0660");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(630, 140, 270, 14);

        jLabel21.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel21.setText("Email: e.marketing@ivorygroups.com");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(630, 110, 280, 14);

        jLabel11.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel11.setText("Coorporate Marketing");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(630, 80, 160, 14);

        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 1, 20));
        jLabel16.setText("Marketing Queries");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(650, 44, 240, 30);

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText("Corporate Offices");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 10, 190, 20);

        jLabel14.setFont(new java.awt.Font("Baskerville Old Face", 1, 20));
        jLabel14.setText("Reservation Queries");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(80, 54, 200, 20);

        jLabel19.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel19.setText("Ivory Contact Centre");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(60, 100, 160, 14);

        jLabel20.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel20.setText("Email: reservation@ivorygroups.com");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(60, 130, 253, 20);

        jLabel30.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel30.setText("Facsimile: +91-11-2389 5000");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(60, 190, 240, 14);

        jLabel25.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel25.setText("Telephone: +91-11-2389 0606");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(60, 160, 260, 14);

        jLabel17.setFont(new java.awt.Font("Baskerville Old Face", 1, 20));
        jLabel17.setText("Media Queries");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(110, 240, 160, 20);

        jLabel22.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel22.setText("Email: corp.comm@ivorygroups.com");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(50, 280, 280, 14);

        jLabel27.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel27.setText("Telephone: +91-11-2389 0600");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(50, 320, 230, 14);

        jLabel32.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel32.setText("Facsimile: +91-11-2389 5050");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(50, 350, 240, 14);

        jLabel18.setFont(new java.awt.Font("Baskerville Old Face", 1, 20));
        jLabel18.setText("Ivory Aviation");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(110, 410, 160, 14);

        jLabel24.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel24.setText("Email: director.aviation@ivorygroups.com");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(50, 460, 310, 14);

        jLabel29.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel29.setText("Telephone: +91-11-2389 0607");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(50, 500, 220, 14);

        jLabel34.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel34.setText("Facsimile: +91-11-2389 5007");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(50, 540, 240, 14);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 40, 1000, 590);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(954, 0, 50, 40);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 650);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1000)/2, (screenSize.height-650)/2, 1000, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         this.dispose();
        new ivory().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

}
