import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ivory.java
 *
 * Created on Jul 24, 2017, 6:22:36 PM
 */

/**
 *
 * @author Ayush
 */
public class ivory extends javax.swing.JFrame {

    /** Creates new form ivory */
    public ivory() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jFrame1.setMinimumSize(new java.awt.Dimension(1000, 650));
        jFrame1.setUndecorated(true);
        jFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFrame1WindowOpened(evt);
            }
        });
        jFrame1.getContentPane().setLayout(null);

        jButton9.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jButton9.setText("Display selected room");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton9);
        jButton9.setBounds(70, 310, 200, 27);

        jTable1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Baskerville Old Face", 0, 20));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nams", "Type of room", "no of room", "Day of ci", "day of co", "no of days", "amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jFrame1.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 70, 670, 220);

        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jButton2.setText("Empty Table");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton2);
        jButton2.setBounds(320, 310, 170, 27);

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 1, 18));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("My Booking");
        jFrame1.getContentPane().add(jLabel10);
        jLabel10.setBounds(400, 0, 200, 50);

        jButton3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jButton3.setText("Update Booking");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton3);
        jButton3.setBounds(740, 450, 180, 27);

        jButton4.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jButton4.setText("refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton4);
        jButton4.setBounds(820, 70, 100, 30);

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel8.setText("Name");
        jFrame1.getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 370, 80, 30);

        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel9.setText("Type of room");
        jFrame1.getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 430, 120, 19);

        jLabel12.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel12.setText("no of room");
        jFrame1.getContentPane().add(jLabel12);
        jLabel12.setBounds(80, 480, 90, 19);

        jLabel13.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel13.setText("day of ci");
        jFrame1.getContentPane().add(jLabel13);
        jLabel13.setBounds(80, 530, 60, 19);

        jLabel14.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel14.setText("day of co");
        jFrame1.getContentPane().add(jLabel14);
        jLabel14.setBounds(440, 380, 70, 19);

        jLabel15.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel15.setText("no of days");
        jFrame1.getContentPane().add(jLabel15);
        jLabel15.setBounds(440, 440, 73, 19);

        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel16.setText("amount");
        jFrame1.getContentPane().add(jLabel16);
        jLabel16.setBounds(450, 510, 80, 19);

        jTextField1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jFrame1.getContentPane().add(jTextField1);
        jTextField1.setBounds(230, 370, 140, 30);

        jTextField2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jFrame1.getContentPane().add(jTextField2);
        jTextField2.setBounds(230, 420, 140, 30);

        jTextField3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jFrame1.getContentPane().add(jTextField3);
        jTextField3.setBounds(230, 470, 140, 30);

        jTextField4.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jTextField4);
        jTextField4.setBounds(230, 520, 140, 30);

        jTextField5.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jFrame1.getContentPane().add(jTextField5);
        jTextField5.setBounds(530, 370, 140, 30);

        jTextField6.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jFrame1.getContentPane().add(jTextField6);
        jTextField6.setBounds(530, 430, 140, 30);

        jTextField7.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jFrame1.getContentPane().add(jTextField7);
        jTextField7.setBounds(530, 500, 140, 30);

        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jFrame1.getContentPane().add(jLabel17);
        jLabel17.setBounds(950, 0, 50, 50);

        jLabel11.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout-2.png"))); // NOI18N
        jFrame1.getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1000, 650);
        jFrame1.getContentPane().add(jOptionPane1);
        jOptionPane1.setBounds(780, 210, 200, 70);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 180, 1000, 450);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(944, 0, 60, 50);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 0, 170, 40);

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 0, 110, 40);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 0, 110, 40);

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 0, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ivory.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 650);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1000)/2, (screenSize.height-650)/2, 1000, 650);
    }// </editor-fold>//GEN-END:initComponents
 Timer t= new Timer(10,new ActionListener()
{
int i=0;
public void actionPerformed(ActionEvent e)
{
switch(i%6)
{
case 0:
        jLabel2.setIcon(new ImageIcon("D:\\xiia\\final\\Ivory hotels & resorts2\\src\\1.jpg"));
break;
case 1:
          jLabel2.setIcon(new ImageIcon("D:\\xiia\\final\\Ivory hotels & resorts2\\src\\2.jpg"));
break;

case 2:
        jLabel2.setIcon(new ImageIcon("D:\\xiia\\abc\\project\\ip\\pics\\3.jpg"));
break;

case 3:
        jLabel2.setIcon(new ImageIcon("D:\\xiia\\abc\\project\\ip\\pics\\4.jpg"));
break;

case 4:
        jLabel2.setIcon(new ImageIcon("D:\\xiia\\abc\\project\\ip\\pics\\5.jpg"));
break;
case 5:
        jLabel2.setIcon(new ImageIcon("D:\\xiia\\abc\\project\\ip\\pics\\6.jpg"));
break;
    default:
    System.out.print("fails");
}
if (i>10)
{
i=0;
}
i++;

}});
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         this.dispose();
        new reservation_3().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
            t.start();
t.setDelay(3000);
    }//GEN-LAST:event_formWindowOpened

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         this.dispose();
        new Contact().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         this.dispose();
        new home().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
      DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int aa=jTable1.getSelectedRow();
        jTextField1.setText((String)jTable1.getValueAt(aa,0));
        jTextField2.setText((String)jTable1.getValueAt(aa,1));
        jTextField3.setText((String)jTable1.getValueAt(aa,2));
        jTextField4.setText((String)jTable1.getValueAt(aa,3));
         jTextField5.setText((String)jTable1.getValueAt(aa,4));
        jTextField6.setText((String)jTable1.getValueAt(aa,5));
        jTextField7.setText((String)jTable1.getValueAt(aa,6));
}//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int rows=model.getRowCount();
       if(rows>0)
       {
           for(int i=0;i<rows;i++)
           {
               model.removeRow(0);
           }
       }
          



}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
     int ans=jOptionPane1.showConfirmDialog(null, "want to update record");
        if(ans==jOptionPane1.YES_OPTION)
        {
        try
        {
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/ivory","root","Ayush@123");
            stmt=con.createStatement();
            String query="Update pay set type_of_room='"+jTextField2.getText()+"',no_of_room='"+jTextField3.getText()+"',date_of_ci='"+jTextField4.getText()+"',date_of_co='"+jTextField5.getText()+"',no_of_days='"+jTextField6.getText()+"',amount='"+jTextField7.getText()+"' where name='"+jTextField1.getText()+"';";
            stmt.executeUpdate(query);
            System.out.println(query);
            jOptionPane1.showMessageDialog(null,"record updated");
        }
        catch(Exception e)
        {
            jOptionPane1.showMessageDialog(null,"error in updation");
             String query="Update pay set type_of_room='"+jTextField2.getText()+"',no_of_room='"+jTextField3.getText()+"',date_of_ci='"+jTextField4.getText()+"',date_of_co='"+jTextField5.getText()+"',no_of_days='"+jTextField6.getText()+"',amount='"+jTextField7.getText()+"' where name='"+jTextField1.getText()+"';";
           System.out.println(query);
        }
        jTextField5.setText("");
        jTextField7.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
          jTextField3.setText("");
        jTextField4.setText("");
        jTextField6.setText("");
        }

}//GEN-LAST:event_jButton3ActionPerformed

    Connection con = null;
Statement stmt = null;
ResultSet rs= null;
    private void jFrame1WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame1WindowOpened
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        jTable1.getModel();
        try {
            Class.forName("java.sql.Driver");
            con  = DriverManager.getConnection("jdbc:mysql://localhost/ivory","root","Ayush@123");
            stmt = con.createStatement();
            //String combo1=(String)jComboBox1.getSelectedItem();
            //String combo2=(String)jComboBox2.getSelectedItem();
            //String Textf=jTextField6.getText();
            String query = "select * from pay;";

            rs  = stmt.executeQuery(query);
            int count=0;
            while(rs.next()) {
                count++;
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)});
            }
            // msg = msg;
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "error in connectivity");
            System.out.print(e);
        }
}//GEN-LAST:event_jFrame1WindowOpened

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:

        
        jFrame1.setVisible(true);
}//GEN-LAST:event_jLabel7MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        jTable1.getModel();
        try {
            Class.forName("java.sql.Driver");
            con  = DriverManager.getConnection("jdbc:mysql://localhost/ivory","root","Ayush@123");
            stmt = con.createStatement();
            //String combo1=(String)jComboBox1.getSelectedItem();
            //String combo2=(String)jComboBox2.getSelectedItem();
            //String Textf=jTextField6.getText();
            String query = "select * from pay;";

            rs  = stmt.executeQuery(query);
            int count=0;
            while(rs.next()) {
                count++;
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)});
            }
            // msg = msg;
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "error in connectivity");
            System.out.print(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
         this.dispose();
        new ivory().setVisible(true);
    }//GEN-LAST:event_jLabel17MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ivory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

}
